=== arranay/Integration_of_cross_platform_software_systems/lab1/system.dtd
<!DOCTYPE INFORMATION_SYSTEM_DESIGN [

<!ELEMENT BPMN-model (model-name, author, date, tracks, streams)>
<!ELEMENT model-name (PCDATA)>
<!ELEMENT author (PCDATA | EMPTY)>
<!ELEMENT date (PCDATA | EMPTY)>
<!ELEMENT tracks (track+)>
<!ELEMENT streams (stream*)>

<!ELEMENT track (track-name, actions, events, forks)>
<!ATTLIST track id ID #REQUIRED>
<!ELEMENT track-name (PCDATA)>
<!ELEMENT actions (action*)>
<!ELEMENT forks (fork*)>
<!ELEMENT events (event*)>

<!ELEMENT action (operation)>
<!ATTLIST action id ID #REQUIRED>
<!ELEMENT operation (PCDATA)>

<!ELEMENT fork (condition)>
<!ATTLIST fork id ID #REQUIRED>
<!ELEMENT condition (PCDATA)>

<!ELEMENT event (event-name)>
<!ATTLIST event id ID #REQUIRED>
<!ATTLIST event type (start | intermediate | end)>
<!ELEMENT event-name (PCDATA | EMPTY)>

<!ENTITY %item>
<!ATTLIST %item id ID #REQUIRED>
<!ATTLIST %item type (action | fork | event)>
<!ATTLIST %item item-id IDREF>

<!ELEMENT stream (from, to, stream-name)>
<!ATTLIST stream id ID #REQUIRED>
<!ELEMENT from (%item)>
<!ELEMENT to (%item)>
<!ELEMENT stream-name (PCDATA | EMPTY)>
]>

=== arranay/Integration_of_cross_platform_software_systems/lab2/lab2/target/classes/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BPMN-model SYSTEM "system.dtd">

<BPMN-model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="system.xsd">
    <model-name>Example</model-name>
    <author>Valeria Khlyzova</author>
    <date>2022-06-06</date>

    <tracks>
        <track id="track1">
            <track-name>Customer</track-name>

            <events>
                <event id="event11" type="start">
                    <event-name>Start</event-name>
                </event>
            </events>

            <actions>
                <action id="action11">
                    <operation>Order and pay for the product</operation>
                    <time>5000</time>
                </action>
            </actions>
        </track>

        <track id="track2">
            <track-name>Seller</track-name>

            <events>
                <event id="event21" type="end">
                    <event-name>End</event-name>
                </event>
            </events>

            <actions>
                <action id="action21">
                    <operation>Check the product in storehouse</operation>
                    <time>7000</time>
                </action>
                <action id="action22">
                    <operation>Send the ordered product</operation>
                    <time>5000</time>
                </action>
                <action id="action23">
                    <operation>Return money</operation>
                    <time>3000</time>
                </action>
            </actions>

            <forks>
                <fork id="fork21">
                    <condition>is the product in storehouse?</condition>
                </fork>
            </forks>
        </track>
    </tracks>

    <streams>
        <stream id="stream1">
            <from id="from1" type="event" item-id="event11" />
            <to id="to1" type="action" item-id="action11" />
        </stream>
        <stream id="stream2">
            <from id="from2" type="action" item-id="action11" />
            <to id="to2" type="action" item-id="action21" />
        </stream>
        <stream id="stream3">
            <from id="from3" type="action" item-id="action21" />
            <to id="to3" type="fork" item-id="fork21" />
        </stream>
        <stream id="stream4">
            <from id="from4" type="fork" item-id="fork21" />
            <to id="to4" type="action" item-id="action23" />
            <stream-name>no</stream-name>
        </stream>
        <stream id="stream5">
            <from id="from5" type="fork" item-id="fork21" />
            <to id="to5" type="action" item-id="action22" />
            <stream-name>yes</stream-name>
        </stream>
        <stream id="stream6">
            <from id="from6" type="action" item-id="action22" />
            <to id="to6" type="event" item-id="event21" />
        </stream>
        <stream id="stream7">
            <from id="from7" type="action" item-id="action23" />
            <to id="to7" type="event" item-id="event21" />
        </stream>
    </streams>
</BPMN-model>
